[package]
name = "pulsebench-scoring"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
pulsebench-types = { version = "0.1.0", path = "../types" }

[dev-dependencies]
chrono = "0.4.45"
